// <auto-generated />
using System;
using API_QLRP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_QLRP.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20240626115017_addDoanhThu")]
    partial class addDoanhThu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_QLRP.Models.DoanhThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DoanhThus");
                });

            modelBuilder.Entity("API_QLRP.Models.Ghe", b =>
                {
                    b.Property<int>("GheID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GheID"));

                    b.Property<int>("PhongChieuID")
                        .HasColumnType("int");

                    b.Property<string>("SoGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GheID");

                    b.ToTable("Ghes");
                });

            modelBuilder.Entity("API_QLRP.Models.LichChieu", b =>
                {
                    b.Property<int>("LichChieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichChieuID"));

                    b.Property<int>("PhimID")
                        .HasColumnType("int");

                    b.Property<int>("PhongChieuID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianChieu")
                        .HasColumnType("datetime2");

                    b.HasKey("LichChieuID");

                    b.ToTable("LichChieus");
                });

            modelBuilder.Entity("API_QLRP.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiDungID");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("API_QLRP.Models.Phim", b =>
                {
                    b.Property<int>("PhimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhimID"));

                    b.Property<decimal>("DanhGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DaoDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosterURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhimID");

                    b.ToTable("Phims");
                });

            modelBuilder.Entity("API_QLRP.Models.PhongChieu", b =>
                {
                    b.Property<int>("PhongChieuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongChieuID"));

                    b.Property<int>("SoPhong")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.HasKey("PhongChieuID");

                    b.ToTable("PhongChieus");
                });

            modelBuilder.Entity("API_QLRP.Models.Ve", b =>
                {
                    b.Property<int>("VeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeID"));

                    b.Property<int>("GheID")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LichChieuID")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianMua")
                        .HasColumnType("datetime2");

                    b.HasKey("VeID");

                    b.ToTable("Ves");
                });
#pragma warning restore 612, 618
        }
    }
}
